/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_eric_jni_JniTest */

#ifndef _Included_com_study_eric_jni_JniTest
#define _Included_com_study_eric_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_eric_jni_JniTest
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_eric_jni_JniTest_getJniString
  (JNIEnv *, jobject);

/*
 * Class:     com_study_eric_jni_JniTest
 * Method:    getStringFromJavaField
 * Signature: (Lcom/study/eric/jni/JavaClass;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_eric_jni_JniTest_getStringFromJavaField
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_study_eric_jni_JniTest
 * Method:    getStringFromJavaInstance
 * Signature: (Lcom/study/eric/jni/JavaClass;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_eric_jni_JniTest_getStringFromJavaInstance
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_study_eric_jni_JniTest
 * Method:    getStringFromJavaThrowing
 * Signature: (Lcom/study/eric/jni/JavaClass;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_study_eric_jni_JniTest_getStringFromJavaThrowing
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_study_eric_jni_JniTest
 * Method:    getFromJniThrowing
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_study_eric_jni_JniTest_getFromJniThrowing
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
